# Generated by Django 5.2 on 2025-06-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_contributor_application_contributor_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('contributor', 'task')},
        ),
    ]
