# Generated by Django 5.2 on 2025-06-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_application_unique_together'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='proposal',
        ),
        migrations.AlterField(
            model_name='application',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='user.contributor'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user.contributor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='contributors',
            field=models.ManyToManyField(default='none', related_name='tasks', to='user.contributor'),
        ),
    ]
