# Generated by Django 5.2 on 2025-06-20 13:12


from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.contributor'),
        ),
    ]
