# Generated by Django 5.2 on 2025-06-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0009_remove_task_contributors_task_contributor'),
        ('user', '0002_myuser_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='In paisa (₹10 = 1000)')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.contributor')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.provider')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
