# Generated by Django 5.2 on 2025-06-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_contributors_and_more'),
        ('user', '0002_myuser_stripe_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contributors',
        ),
        migrations.AddField(
            model_name='task',
            name='contributor',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.contributor'),
        ),
    ]
